// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopProductsVisitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProductsVisitsRequest) Reset() {
	*x = TopProductsVisitsRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProductsVisitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProductsVisitsRequest) ProtoMessage() {}

func (x *TopProductsVisitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProductsVisitsRequest.ProtoReflect.Descriptor instead.
func (*TopProductsVisitsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TopProductsVisitsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type TopProductsVisitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductVisits []*ProductVisit        `protobuf:"bytes,1,rep,name=product_visits,json=productVisits,proto3" json:"product_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopProductsVisitsResponse) Reset() {
	*x = TopProductsVisitsResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopProductsVisitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopProductsVisitsResponse) ProtoMessage() {}

func (x *TopProductsVisitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopProductsVisitsResponse.ProtoReflect.Descriptor instead.
func (*TopProductsVisitsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TopProductsVisitsResponse) GetProductVisits() []*ProductVisit {
	if x != nil {
		return x.ProductVisits
	}
	return nil
}

type ProductVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageURL       string                 `protobuf:"bytes,1,opt,name=PageURL,proto3" json:"PageURL,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductVisit) Reset() {
	*x = ProductVisit{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductVisit) ProtoMessage() {}

func (x *ProductVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductVisit.ProtoReflect.Descriptor instead.
func (*ProductVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *ProductVisit) GetPageURL() string {
	if x != nil {
		return x.PageURL
	}
	return ""
}

func (x *ProductVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsPerDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerDayRequest) Reset() {
	*x = VisitsPerDayRequest{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerDayRequest) ProtoMessage() {}

func (x *VisitsPerDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerDayRequest.ProtoReflect.Descriptor instead.
func (*VisitsPerDayRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

type VisitsPerDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayVisits     []*DayVisit            `protobuf:"bytes,1,rep,name=day_visits,json=dayVisits,proto3" json:"day_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerDayResponse) Reset() {
	*x = VisitsPerDayResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerDayResponse) ProtoMessage() {}

func (x *VisitsPerDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerDayResponse.ProtoReflect.Descriptor instead.
func (*VisitsPerDayResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *VisitsPerDayResponse) GetDayVisits() []*DayVisit {
	if x != nil {
		return x.DayVisits
	}
	return nil
}

type DayVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=Date,proto3" json:"Date,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayVisit) Reset() {
	*x = DayVisit{}
	mi := &file_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayVisit) ProtoMessage() {}

func (x *DayVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayVisit.ProtoReflect.Descriptor instead.
func (*DayVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *DayVisit) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DayVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsPerMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerMonthRequest) Reset() {
	*x = VisitsPerMonthRequest{}
	mi := &file_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerMonthRequest) ProtoMessage() {}

func (x *VisitsPerMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerMonthRequest.ProtoReflect.Descriptor instead.
func (*VisitsPerMonthRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{6}
}

type VisitsPerMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonthVisits   []*MonthVisit          `protobuf:"bytes,1,rep,name=month_visits,json=monthVisits,proto3" json:"month_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerMonthResponse) Reset() {
	*x = VisitsPerMonthResponse{}
	mi := &file_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerMonthResponse) ProtoMessage() {}

func (x *VisitsPerMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerMonthResponse.ProtoReflect.Descriptor instead.
func (*VisitsPerMonthResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *VisitsPerMonthResponse) GetMonthVisits() []*MonthVisit {
	if x != nil {
		return x.MonthVisits
	}
	return nil
}

type MonthVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=Month,proto3" json:"Month,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthVisit) Reset() {
	*x = MonthVisit{}
	mi := &file_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthVisit) ProtoMessage() {}

func (x *MonthVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthVisit.ProtoReflect.Descriptor instead.
func (*MonthVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *MonthVisit) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsPerCountryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerCountryRequest) Reset() {
	*x = VisitsPerCountryRequest{}
	mi := &file_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerCountryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerCountryRequest) ProtoMessage() {}

func (x *VisitsPerCountryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerCountryRequest.ProtoReflect.Descriptor instead.
func (*VisitsPerCountryRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{9}
}

type VisitsPerCountryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryVisits []*CountryVisit        `protobuf:"bytes,1,rep,name=country_visits,json=countryVisits,proto3" json:"country_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerCountryResponse) Reset() {
	*x = VisitsPerCountryResponse{}
	mi := &file_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerCountryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerCountryResponse) ProtoMessage() {}

func (x *VisitsPerCountryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerCountryResponse.ProtoReflect.Descriptor instead.
func (*VisitsPerCountryResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *VisitsPerCountryResponse) GetCountryVisits() []*CountryVisit {
	if x != nil {
		return x.CountryVisits
	}
	return nil
}

type CountryVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=Country,proto3" json:"Country,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryVisit) Reset() {
	*x = CountryVisit{}
	mi := &file_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryVisit) ProtoMessage() {}

func (x *CountryVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryVisit.ProtoReflect.Descriptor instead.
func (*CountryVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *CountryVisit) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CountryVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsPerCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerCityRequest) Reset() {
	*x = VisitsPerCityRequest{}
	mi := &file_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerCityRequest) ProtoMessage() {}

func (x *VisitsPerCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerCityRequest.ProtoReflect.Descriptor instead.
func (*VisitsPerCityRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{12}
}

type VisitsPerCityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityVisits    []*CityVisit           `protobuf:"bytes,1,rep,name=city_visits,json=cityVisits,proto3" json:"city_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsPerCityResponse) Reset() {
	*x = VisitsPerCityResponse{}
	mi := &file_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsPerCityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsPerCityResponse) ProtoMessage() {}

func (x *VisitsPerCityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsPerCityResponse.ProtoReflect.Descriptor instead.
func (*VisitsPerCityResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *VisitsPerCityResponse) GetCityVisits() []*CityVisit {
	if x != nil {
		return x.CityVisits
	}
	return nil
}

type CityVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=City,proto3" json:"City,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityVisit) Reset() {
	*x = CityVisit{}
	mi := &file_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityVisit) ProtoMessage() {}

func (x *CityVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityVisit.ProtoReflect.Descriptor instead.
func (*CityVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *CityVisit) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsFromEgyptPerDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerDayRequest) Reset() {
	*x = VisitsFromEgyptPerDayRequest{}
	mi := &file_analytics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerDayRequest) ProtoMessage() {}

func (x *VisitsFromEgyptPerDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerDayRequest.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerDayRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{15}
}

type VisitsFromEgyptPerDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayVisits     []*DayVisit            `protobuf:"bytes,1,rep,name=day_visits,json=dayVisits,proto3" json:"day_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerDayResponse) Reset() {
	*x = VisitsFromEgyptPerDayResponse{}
	mi := &file_analytics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerDayResponse) ProtoMessage() {}

func (x *VisitsFromEgyptPerDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerDayResponse.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerDayResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{16}
}

func (x *VisitsFromEgyptPerDayResponse) GetDayVisits() []*DayVisit {
	if x != nil {
		return x.DayVisits
	}
	return nil
}

type VisitsFromOtherCountriesPerDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromOtherCountriesPerDayRequest) Reset() {
	*x = VisitsFromOtherCountriesPerDayRequest{}
	mi := &file_analytics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromOtherCountriesPerDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromOtherCountriesPerDayRequest) ProtoMessage() {}

func (x *VisitsFromOtherCountriesPerDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromOtherCountriesPerDayRequest.ProtoReflect.Descriptor instead.
func (*VisitsFromOtherCountriesPerDayRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{17}
}

type VisitsFromOtherCountriesPerDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DayVisits     []*DayVisit            `protobuf:"bytes,1,rep,name=day_visits,json=dayVisits,proto3" json:"day_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromOtherCountriesPerDayResponse) Reset() {
	*x = VisitsFromOtherCountriesPerDayResponse{}
	mi := &file_analytics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromOtherCountriesPerDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromOtherCountriesPerDayResponse) ProtoMessage() {}

func (x *VisitsFromOtherCountriesPerDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromOtherCountriesPerDayResponse.ProtoReflect.Descriptor instead.
func (*VisitsFromOtherCountriesPerDayResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{18}
}

func (x *VisitsFromOtherCountriesPerDayResponse) GetDayVisits() []*DayVisit {
	if x != nil {
		return x.DayVisits
	}
	return nil
}

type VisitsFromEgyptPerHourPastMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerHourPastMonthRequest) Reset() {
	*x = VisitsFromEgyptPerHourPastMonthRequest{}
	mi := &file_analytics_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerHourPastMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerHourPastMonthRequest) ProtoMessage() {}

func (x *VisitsFromEgyptPerHourPastMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerHourPastMonthRequest.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerHourPastMonthRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{19}
}

type VisitsFromEgyptPerHourPastMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HourVisits    []*HourVisit           `protobuf:"bytes,1,rep,name=hour_visits,json=hourVisits,proto3" json:"hour_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerHourPastMonthResponse) Reset() {
	*x = VisitsFromEgyptPerHourPastMonthResponse{}
	mi := &file_analytics_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerHourPastMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerHourPastMonthResponse) ProtoMessage() {}

func (x *VisitsFromEgyptPerHourPastMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerHourPastMonthResponse.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerHourPastMonthResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{20}
}

func (x *VisitsFromEgyptPerHourPastMonthResponse) GetHourVisits() []*HourVisit {
	if x != nil {
		return x.HourVisits
	}
	return nil
}

type HourVisit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          string                 `protobuf:"bytes,1,opt,name=Hour,proto3" json:"Hour,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=Total,proto3" json:"Total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourVisit) Reset() {
	*x = HourVisit{}
	mi := &file_analytics_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourVisit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourVisit) ProtoMessage() {}

func (x *HourVisit) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourVisit.ProtoReflect.Descriptor instead.
func (*HourVisit) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{21}
}

func (x *HourVisit) GetHour() string {
	if x != nil {
		return x.Hour
	}
	return ""
}

func (x *HourVisit) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type VisitsFromEgyptPerHourTodayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerHourTodayRequest) Reset() {
	*x = VisitsFromEgyptPerHourTodayRequest{}
	mi := &file_analytics_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerHourTodayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerHourTodayRequest) ProtoMessage() {}

func (x *VisitsFromEgyptPerHourTodayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerHourTodayRequest.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerHourTodayRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{22}
}

type VisitsFromEgyptPerHourTodayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HourVisits    []*HourVisit           `protobuf:"bytes,1,rep,name=hour_visits,json=hourVisits,proto3" json:"hour_visits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisitsFromEgyptPerHourTodayResponse) Reset() {
	*x = VisitsFromEgyptPerHourTodayResponse{}
	mi := &file_analytics_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitsFromEgyptPerHourTodayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitsFromEgyptPerHourTodayResponse) ProtoMessage() {}

func (x *VisitsFromEgyptPerHourTodayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitsFromEgyptPerHourTodayResponse.ProtoReflect.Descriptor instead.
func (*VisitsFromEgyptPerHourTodayResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{23}
}

func (x *VisitsFromEgyptPerHourTodayResponse) GetHourVisits() []*HourVisit {
	if x != nil {
		return x.HourVisits
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\"0\n" +
	"\x18TopProductsVisitsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"[\n" +
	"\x19TopProductsVisitsResponse\x12>\n" +
	"\x0eproduct_visits\x18\x01 \x03(\v2\x17.analytics.ProductVisitR\rproductVisits\">\n" +
	"\fProductVisit\x12\x18\n" +
	"\aPageURL\x18\x01 \x01(\tR\aPageURL\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"\x15\n" +
	"\x13VisitsPerDayRequest\"J\n" +
	"\x14VisitsPerDayResponse\x122\n" +
	"\n" +
	"day_visits\x18\x01 \x03(\v2\x13.analytics.DayVisitR\tdayVisits\"4\n" +
	"\bDayVisit\x12\x12\n" +
	"\x04Date\x18\x01 \x01(\tR\x04Date\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"\x17\n" +
	"\x15VisitsPerMonthRequest\"R\n" +
	"\x16VisitsPerMonthResponse\x128\n" +
	"\fmonth_visits\x18\x01 \x03(\v2\x15.analytics.MonthVisitR\vmonthVisits\"8\n" +
	"\n" +
	"MonthVisit\x12\x14\n" +
	"\x05Month\x18\x01 \x01(\tR\x05Month\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"\x19\n" +
	"\x17VisitsPerCountryRequest\"Z\n" +
	"\x18VisitsPerCountryResponse\x12>\n" +
	"\x0ecountry_visits\x18\x01 \x03(\v2\x17.analytics.CountryVisitR\rcountryVisits\">\n" +
	"\fCountryVisit\x12\x18\n" +
	"\aCountry\x18\x01 \x01(\tR\aCountry\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"\x16\n" +
	"\x14VisitsPerCityRequest\"N\n" +
	"\x15VisitsPerCityResponse\x125\n" +
	"\vcity_visits\x18\x01 \x03(\v2\x14.analytics.CityVisitR\n" +
	"cityVisits\"5\n" +
	"\tCityVisit\x12\x12\n" +
	"\x04City\x18\x01 \x01(\tR\x04City\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"\x1e\n" +
	"\x1cVisitsFromEgyptPerDayRequest\"S\n" +
	"\x1dVisitsFromEgyptPerDayResponse\x122\n" +
	"\n" +
	"day_visits\x18\x01 \x03(\v2\x13.analytics.DayVisitR\tdayVisits\"'\n" +
	"%VisitsFromOtherCountriesPerDayRequest\"\\\n" +
	"&VisitsFromOtherCountriesPerDayResponse\x122\n" +
	"\n" +
	"day_visits\x18\x01 \x03(\v2\x13.analytics.DayVisitR\tdayVisits\"(\n" +
	"&VisitsFromEgyptPerHourPastMonthRequest\"`\n" +
	"'VisitsFromEgyptPerHourPastMonthResponse\x125\n" +
	"\vhour_visits\x18\x01 \x03(\v2\x14.analytics.HourVisitR\n" +
	"hourVisits\"5\n" +
	"\tHourVisit\x12\x12\n" +
	"\x04Hour\x18\x01 \x01(\tR\x04Hour\x12\x14\n" +
	"\x05Total\x18\x02 \x01(\x05R\x05Total\"$\n" +
	"\"VisitsFromEgyptPerHourTodayRequest\"\\\n" +
	"#VisitsFromEgyptPerHourTodayResponse\x125\n" +
	"\vhour_visits\x18\x01 \x03(\v2\x14.analytics.HourVisitR\n" +
	"hourVisits2\xce\a\n" +
	"\x10AnalyticsService\x12^\n" +
	"\x11TopProductsVisits\x12#.analytics.TopProductsVisitsRequest\x1a$.analytics.TopProductsVisitsResponse\x12O\n" +
	"\fVisitsPerDay\x12\x1e.analytics.VisitsPerDayRequest\x1a\x1f.analytics.VisitsPerDayResponse\x12U\n" +
	"\x0eVisitsPerMonth\x12 .analytics.VisitsPerMonthRequest\x1a!.analytics.VisitsPerMonthResponse\x12[\n" +
	"\x10VisitsPerCountry\x12\".analytics.VisitsPerCountryRequest\x1a#.analytics.VisitsPerCountryResponse\x12R\n" +
	"\rVisitsPerCity\x12\x1f.analytics.VisitsPerCityRequest\x1a .analytics.VisitsPerCityResponse\x12j\n" +
	"\x15VisitsFromEgyptPerDay\x12'.analytics.VisitsFromEgyptPerDayRequest\x1a(.analytics.VisitsFromEgyptPerDayResponse\x12\x85\x01\n" +
	"\x1eVisitsFromOtherCountriesPerDay\x120.analytics.VisitsFromOtherCountriesPerDayRequest\x1a1.analytics.VisitsFromOtherCountriesPerDayResponse\x12\x8b\x01\n" +
	"\"VisitsFromEgyptPerHourForPastMonth\x121.analytics.VisitsFromEgyptPerHourPastMonthRequest\x1a2.analytics.VisitsFromEgyptPerHourPastMonthResponse\x12\x7f\n" +
	"\x1eVisitsFromEgyptPerHourForToday\x12-.analytics.VisitsFromEgyptPerHourTodayRequest\x1a..analytics.VisitsFromEgyptPerHourTodayResponseB\x15Z\x13madastore/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_analytics_proto_goTypes = []any{
	(*TopProductsVisitsRequest)(nil),                // 0: analytics.TopProductsVisitsRequest
	(*TopProductsVisitsResponse)(nil),               // 1: analytics.TopProductsVisitsResponse
	(*ProductVisit)(nil),                            // 2: analytics.ProductVisit
	(*VisitsPerDayRequest)(nil),                     // 3: analytics.VisitsPerDayRequest
	(*VisitsPerDayResponse)(nil),                    // 4: analytics.VisitsPerDayResponse
	(*DayVisit)(nil),                                // 5: analytics.DayVisit
	(*VisitsPerMonthRequest)(nil),                   // 6: analytics.VisitsPerMonthRequest
	(*VisitsPerMonthResponse)(nil),                  // 7: analytics.VisitsPerMonthResponse
	(*MonthVisit)(nil),                              // 8: analytics.MonthVisit
	(*VisitsPerCountryRequest)(nil),                 // 9: analytics.VisitsPerCountryRequest
	(*VisitsPerCountryResponse)(nil),                // 10: analytics.VisitsPerCountryResponse
	(*CountryVisit)(nil),                            // 11: analytics.CountryVisit
	(*VisitsPerCityRequest)(nil),                    // 12: analytics.VisitsPerCityRequest
	(*VisitsPerCityResponse)(nil),                   // 13: analytics.VisitsPerCityResponse
	(*CityVisit)(nil),                               // 14: analytics.CityVisit
	(*VisitsFromEgyptPerDayRequest)(nil),            // 15: analytics.VisitsFromEgyptPerDayRequest
	(*VisitsFromEgyptPerDayResponse)(nil),           // 16: analytics.VisitsFromEgyptPerDayResponse
	(*VisitsFromOtherCountriesPerDayRequest)(nil),   // 17: analytics.VisitsFromOtherCountriesPerDayRequest
	(*VisitsFromOtherCountriesPerDayResponse)(nil),  // 18: analytics.VisitsFromOtherCountriesPerDayResponse
	(*VisitsFromEgyptPerHourPastMonthRequest)(nil),  // 19: analytics.VisitsFromEgyptPerHourPastMonthRequest
	(*VisitsFromEgyptPerHourPastMonthResponse)(nil), // 20: analytics.VisitsFromEgyptPerHourPastMonthResponse
	(*HourVisit)(nil),                               // 21: analytics.HourVisit
	(*VisitsFromEgyptPerHourTodayRequest)(nil),      // 22: analytics.VisitsFromEgyptPerHourTodayRequest
	(*VisitsFromEgyptPerHourTodayResponse)(nil),     // 23: analytics.VisitsFromEgyptPerHourTodayResponse
}
var file_analytics_proto_depIdxs = []int32{
	2,  // 0: analytics.TopProductsVisitsResponse.product_visits:type_name -> analytics.ProductVisit
	5,  // 1: analytics.VisitsPerDayResponse.day_visits:type_name -> analytics.DayVisit
	8,  // 2: analytics.VisitsPerMonthResponse.month_visits:type_name -> analytics.MonthVisit
	11, // 3: analytics.VisitsPerCountryResponse.country_visits:type_name -> analytics.CountryVisit
	14, // 4: analytics.VisitsPerCityResponse.city_visits:type_name -> analytics.CityVisit
	5,  // 5: analytics.VisitsFromEgyptPerDayResponse.day_visits:type_name -> analytics.DayVisit
	5,  // 6: analytics.VisitsFromOtherCountriesPerDayResponse.day_visits:type_name -> analytics.DayVisit
	21, // 7: analytics.VisitsFromEgyptPerHourPastMonthResponse.hour_visits:type_name -> analytics.HourVisit
	21, // 8: analytics.VisitsFromEgyptPerHourTodayResponse.hour_visits:type_name -> analytics.HourVisit
	0,  // 9: analytics.AnalyticsService.TopProductsVisits:input_type -> analytics.TopProductsVisitsRequest
	3,  // 10: analytics.AnalyticsService.VisitsPerDay:input_type -> analytics.VisitsPerDayRequest
	6,  // 11: analytics.AnalyticsService.VisitsPerMonth:input_type -> analytics.VisitsPerMonthRequest
	9,  // 12: analytics.AnalyticsService.VisitsPerCountry:input_type -> analytics.VisitsPerCountryRequest
	12, // 13: analytics.AnalyticsService.VisitsPerCity:input_type -> analytics.VisitsPerCityRequest
	15, // 14: analytics.AnalyticsService.VisitsFromEgyptPerDay:input_type -> analytics.VisitsFromEgyptPerDayRequest
	17, // 15: analytics.AnalyticsService.VisitsFromOtherCountriesPerDay:input_type -> analytics.VisitsFromOtherCountriesPerDayRequest
	19, // 16: analytics.AnalyticsService.VisitsFromEgyptPerHourForPastMonth:input_type -> analytics.VisitsFromEgyptPerHourPastMonthRequest
	22, // 17: analytics.AnalyticsService.VisitsFromEgyptPerHourForToday:input_type -> analytics.VisitsFromEgyptPerHourTodayRequest
	1,  // 18: analytics.AnalyticsService.TopProductsVisits:output_type -> analytics.TopProductsVisitsResponse
	4,  // 19: analytics.AnalyticsService.VisitsPerDay:output_type -> analytics.VisitsPerDayResponse
	7,  // 20: analytics.AnalyticsService.VisitsPerMonth:output_type -> analytics.VisitsPerMonthResponse
	10, // 21: analytics.AnalyticsService.VisitsPerCountry:output_type -> analytics.VisitsPerCountryResponse
	13, // 22: analytics.AnalyticsService.VisitsPerCity:output_type -> analytics.VisitsPerCityResponse
	16, // 23: analytics.AnalyticsService.VisitsFromEgyptPerDay:output_type -> analytics.VisitsFromEgyptPerDayResponse
	18, // 24: analytics.AnalyticsService.VisitsFromOtherCountriesPerDay:output_type -> analytics.VisitsFromOtherCountriesPerDayResponse
	20, // 25: analytics.AnalyticsService.VisitsFromEgyptPerHourForPastMonth:output_type -> analytics.VisitsFromEgyptPerHourPastMonthResponse
	23, // 26: analytics.AnalyticsService.VisitsFromEgyptPerHourForToday:output_type -> analytics.VisitsFromEgyptPerHourTodayResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
