// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_TopProductsVisits_FullMethodName                  = "/analytics.AnalyticsService/TopProductsVisits"
	AnalyticsService_VisitsPerDay_FullMethodName                       = "/analytics.AnalyticsService/VisitsPerDay"
	AnalyticsService_VisitsPerMonth_FullMethodName                     = "/analytics.AnalyticsService/VisitsPerMonth"
	AnalyticsService_VisitsPerCountry_FullMethodName                   = "/analytics.AnalyticsService/VisitsPerCountry"
	AnalyticsService_VisitsPerCity_FullMethodName                      = "/analytics.AnalyticsService/VisitsPerCity"
	AnalyticsService_VisitsFromEgyptPerDay_FullMethodName              = "/analytics.AnalyticsService/VisitsFromEgyptPerDay"
	AnalyticsService_VisitsFromOtherCountriesPerDay_FullMethodName     = "/analytics.AnalyticsService/VisitsFromOtherCountriesPerDay"
	AnalyticsService_VisitsFromEgyptPerHourForPastMonth_FullMethodName = "/analytics.AnalyticsService/VisitsFromEgyptPerHourForPastMonth"
	AnalyticsService_VisitsFromEgyptPerHourForToday_FullMethodName     = "/analytics.AnalyticsService/VisitsFromEgyptPerHourForToday"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	TopProductsVisits(ctx context.Context, in *TopProductsVisitsRequest, opts ...grpc.CallOption) (*TopProductsVisitsResponse, error)
	VisitsPerDay(ctx context.Context, in *VisitsPerDayRequest, opts ...grpc.CallOption) (*VisitsPerDayResponse, error)
	VisitsPerMonth(ctx context.Context, in *VisitsPerMonthRequest, opts ...grpc.CallOption) (*VisitsPerMonthResponse, error)
	VisitsPerCountry(ctx context.Context, in *VisitsPerCountryRequest, opts ...grpc.CallOption) (*VisitsPerCountryResponse, error)
	VisitsPerCity(ctx context.Context, in *VisitsPerCityRequest, opts ...grpc.CallOption) (*VisitsPerCityResponse, error)
	VisitsFromEgyptPerDay(ctx context.Context, in *VisitsFromEgyptPerDayRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerDayResponse, error)
	VisitsFromOtherCountriesPerDay(ctx context.Context, in *VisitsFromOtherCountriesPerDayRequest, opts ...grpc.CallOption) (*VisitsFromOtherCountriesPerDayResponse, error)
	VisitsFromEgyptPerHourForPastMonth(ctx context.Context, in *VisitsFromEgyptPerHourPastMonthRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerHourPastMonthResponse, error)
	VisitsFromEgyptPerHourForToday(ctx context.Context, in *VisitsFromEgyptPerHourTodayRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerHourTodayResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) TopProductsVisits(ctx context.Context, in *TopProductsVisitsRequest, opts ...grpc.CallOption) (*TopProductsVisitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopProductsVisitsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_TopProductsVisits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsPerDay(ctx context.Context, in *VisitsPerDayRequest, opts ...grpc.CallOption) (*VisitsPerDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsPerDayResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsPerDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsPerMonth(ctx context.Context, in *VisitsPerMonthRequest, opts ...grpc.CallOption) (*VisitsPerMonthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsPerMonthResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsPerMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsPerCountry(ctx context.Context, in *VisitsPerCountryRequest, opts ...grpc.CallOption) (*VisitsPerCountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsPerCountryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsPerCountry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsPerCity(ctx context.Context, in *VisitsPerCityRequest, opts ...grpc.CallOption) (*VisitsPerCityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsPerCityResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsPerCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsFromEgyptPerDay(ctx context.Context, in *VisitsFromEgyptPerDayRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsFromEgyptPerDayResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsFromEgyptPerDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsFromOtherCountriesPerDay(ctx context.Context, in *VisitsFromOtherCountriesPerDayRequest, opts ...grpc.CallOption) (*VisitsFromOtherCountriesPerDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsFromOtherCountriesPerDayResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsFromOtherCountriesPerDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsFromEgyptPerHourForPastMonth(ctx context.Context, in *VisitsFromEgyptPerHourPastMonthRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerHourPastMonthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsFromEgyptPerHourPastMonthResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsFromEgyptPerHourForPastMonth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) VisitsFromEgyptPerHourForToday(ctx context.Context, in *VisitsFromEgyptPerHourTodayRequest, opts ...grpc.CallOption) (*VisitsFromEgyptPerHourTodayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VisitsFromEgyptPerHourTodayResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_VisitsFromEgyptPerHourForToday_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	TopProductsVisits(context.Context, *TopProductsVisitsRequest) (*TopProductsVisitsResponse, error)
	VisitsPerDay(context.Context, *VisitsPerDayRequest) (*VisitsPerDayResponse, error)
	VisitsPerMonth(context.Context, *VisitsPerMonthRequest) (*VisitsPerMonthResponse, error)
	VisitsPerCountry(context.Context, *VisitsPerCountryRequest) (*VisitsPerCountryResponse, error)
	VisitsPerCity(context.Context, *VisitsPerCityRequest) (*VisitsPerCityResponse, error)
	VisitsFromEgyptPerDay(context.Context, *VisitsFromEgyptPerDayRequest) (*VisitsFromEgyptPerDayResponse, error)
	VisitsFromOtherCountriesPerDay(context.Context, *VisitsFromOtherCountriesPerDayRequest) (*VisitsFromOtherCountriesPerDayResponse, error)
	VisitsFromEgyptPerHourForPastMonth(context.Context, *VisitsFromEgyptPerHourPastMonthRequest) (*VisitsFromEgyptPerHourPastMonthResponse, error)
	VisitsFromEgyptPerHourForToday(context.Context, *VisitsFromEgyptPerHourTodayRequest) (*VisitsFromEgyptPerHourTodayResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) TopProductsVisits(context.Context, *TopProductsVisitsRequest) (*TopProductsVisitsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopProductsVisits not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsPerDay(context.Context, *VisitsPerDayRequest) (*VisitsPerDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsPerDay not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsPerMonth(context.Context, *VisitsPerMonthRequest) (*VisitsPerMonthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsPerMonth not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsPerCountry(context.Context, *VisitsPerCountryRequest) (*VisitsPerCountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsPerCountry not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsPerCity(context.Context, *VisitsPerCityRequest) (*VisitsPerCityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsPerCity not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsFromEgyptPerDay(context.Context, *VisitsFromEgyptPerDayRequest) (*VisitsFromEgyptPerDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsFromEgyptPerDay not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsFromOtherCountriesPerDay(context.Context, *VisitsFromOtherCountriesPerDayRequest) (*VisitsFromOtherCountriesPerDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsFromOtherCountriesPerDay not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsFromEgyptPerHourForPastMonth(context.Context, *VisitsFromEgyptPerHourPastMonthRequest) (*VisitsFromEgyptPerHourPastMonthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsFromEgyptPerHourForPastMonth not implemented")
}
func (UnimplementedAnalyticsServiceServer) VisitsFromEgyptPerHourForToday(context.Context, *VisitsFromEgyptPerHourTodayRequest) (*VisitsFromEgyptPerHourTodayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VisitsFromEgyptPerHourForToday not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_TopProductsVisits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopProductsVisitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).TopProductsVisits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_TopProductsVisits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).TopProductsVisits(ctx, req.(*TopProductsVisitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsPerDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsPerDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsPerDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsPerDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsPerDay(ctx, req.(*VisitsPerDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsPerMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsPerMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsPerMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsPerMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsPerMonth(ctx, req.(*VisitsPerMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsPerCountry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsPerCountryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsPerCountry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsPerCountry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsPerCountry(ctx, req.(*VisitsPerCountryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsPerCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsPerCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsPerCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsPerCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsPerCity(ctx, req.(*VisitsPerCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsFromEgyptPerDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsFromEgyptPerDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsFromEgyptPerDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerDay(ctx, req.(*VisitsFromEgyptPerDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsFromOtherCountriesPerDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsFromOtherCountriesPerDayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsFromOtherCountriesPerDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsFromOtherCountriesPerDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsFromOtherCountriesPerDay(ctx, req.(*VisitsFromOtherCountriesPerDayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsFromEgyptPerHourForPastMonth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsFromEgyptPerHourPastMonthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerHourForPastMonth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsFromEgyptPerHourForPastMonth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerHourForPastMonth(ctx, req.(*VisitsFromEgyptPerHourPastMonthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_VisitsFromEgyptPerHourForToday_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VisitsFromEgyptPerHourTodayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerHourForToday(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_VisitsFromEgyptPerHourForToday_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).VisitsFromEgyptPerHourForToday(ctx, req.(*VisitsFromEgyptPerHourTodayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopProductsVisits",
			Handler:    _AnalyticsService_TopProductsVisits_Handler,
		},
		{
			MethodName: "VisitsPerDay",
			Handler:    _AnalyticsService_VisitsPerDay_Handler,
		},
		{
			MethodName: "VisitsPerMonth",
			Handler:    _AnalyticsService_VisitsPerMonth_Handler,
		},
		{
			MethodName: "VisitsPerCountry",
			Handler:    _AnalyticsService_VisitsPerCountry_Handler,
		},
		{
			MethodName: "VisitsPerCity",
			Handler:    _AnalyticsService_VisitsPerCity_Handler,
		},
		{
			MethodName: "VisitsFromEgyptPerDay",
			Handler:    _AnalyticsService_VisitsFromEgyptPerDay_Handler,
		},
		{
			MethodName: "VisitsFromOtherCountriesPerDay",
			Handler:    _AnalyticsService_VisitsFromOtherCountriesPerDay_Handler,
		},
		{
			MethodName: "VisitsFromEgyptPerHourForPastMonth",
			Handler:    _AnalyticsService_VisitsFromEgyptPerHourForPastMonth_Handler,
		},
		{
			MethodName: "VisitsFromEgyptPerHourForToday",
			Handler:    _AnalyticsService_VisitsFromEgyptPerHourForToday_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
